### ISSUE TITLE
Refactor Resources/Libraries/File Structure

### ISSUE THREAD

**Issue by atla5** [RITJBF/JBioFramework#19]
- [ ] imported libraries are located in both `libraries/` and `src/main/java/external`.
- [ ] move all build/gradle files into new `build` or existing `gradle` folder (.travis.yml, gradlew(.bat), 
- [ ] remove `oldstuff/`
- [ ] rename `extrafiles` to `res` and/or `out`.  (Sample Files in `extrafiles/` and  `src/main/java/SampleFiles`)
- [ ] move `extrafiles/HTML Files/Help` files into separate repository, or remove entirely (wiki)

**Comment by joshuapouliot27** [comment]
Most of these issues have been fixed in the Library branch.  The proper place for those build files are in the root directory as both Travis-CI and Gradle expect them to be there.  The last 2 will be dealt with before the next major release.
